CREATE TABLE IF NOT EXISTS portfolio_targets (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    run_id          VARCHAR(32)   NOT NULL,
    trade_date      DATE          NOT NULL,
    symbol          VARCHAR(20)   NOT NULL,
    shares          INT           NOT NULL,
    entry_price     DOUBLE        NOT NULL,
    target_weight   DOUBLE        NOT NULL,
    sector          VARCHAR(60)   NULL,
    score_used      DOUBLE        NULL,
    score_source    VARCHAR(40)   NULL,
    conviction_score    DOUBLE       NULL,
    sizing_method       VARCHAR(20)  NULL,
    kelly_fraction      DOUBLE       NULL,
    company_idio_score      DOUBLE       NULL,
    macro_regime_score      DOUBLE       NULL,
    company_idio_signal_norm DOUBLE      NULL,
    macro_regime_signal_norm DOUBLE      NULL,
    company_idio_component  DOUBLE       NULL,
    macro_regime_component  DOUBLE       NULL,
    quant_component         DOUBLE       NULL,
    walk_forward_sentiment_weight DOUBLE NULL,
    walk_forward_macro_weight DOUBLE     NULL,
    walk_forward_quant_weight DOUBLE     NULL,
    calibration_run_id      VARCHAR(64)  NULL,
    calibration_source      VARCHAR(64)  NULL,
    account_id      VARCHAR(32)   NULL DEFAULT 'default',
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_pt_run       (run_id),
    INDEX idx_pt_date_sym  (trade_date, symbol),
    INDEX idx_pt_account   (account_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
