CREATE TABLE IF NOT EXISTS portfolio_targets (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    run_id          VARCHAR(32)   NOT NULL,
    account_id      VARCHAR(32)   NOT NULL DEFAULT 'default',
    trade_date      DATE          NOT NULL,
    symbol          VARCHAR(20)   NOT NULL,
    candidate_rank  INT           NULL,
    decision_rank   INT           NULL,
    selector_signal_mode VARCHAR(32) NULL,
    selection_explanation VARCHAR(255) NULL,
    selector_earnings_blackout TINYINT(1) NULL,
    side            VARCHAR(10)   NOT NULL DEFAULT 'long',
    shares          INT           NOT NULL,
    entry_price     DOUBLE        NOT NULL,
    atr_20          DOUBLE        NULL,
    price_asof_date DATE          NULL,
    stop_price_initial DOUBLE     NULL,
    risk_per_share  DOUBLE        NULL,
    risk_budget_dollars DOUBLE    NULL,
    initial_risk_dollars DOUBLE   NULL,
    target_notional DOUBLE        NULL,
    target_weight   DOUBLE        NOT NULL,
    sector          VARCHAR(60)   NULL,
    score_used      DOUBLE        NULL,
    score_source    VARCHAR(40)   NULL,
    conviction_score    DOUBLE       NULL,
    sizing_method       VARCHAR(100)  NULL,
    kelly_fraction      DOUBLE       NULL,
    atr_asof_date       DATE         NULL,
    company_idio_score      DOUBLE       NULL,
    macro_regime_score      DOUBLE       NULL,
    company_idio_signal_norm DOUBLE      NULL,
    macro_regime_signal_norm DOUBLE      NULL,
    company_idio_component  DOUBLE       NULL,
    macro_regime_component  DOUBLE       NULL,
    quant_component         DOUBLE       NULL,
    walk_forward_sentiment_weight DOUBLE NULL,
    walk_forward_macro_weight DOUBLE     NULL,
    walk_forward_quant_weight DOUBLE     NULL,
    calibration_run_id      VARCHAR(64)  NULL,
    calibration_source      VARCHAR(64)  NULL,
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_pt_run_symbol_account (run_id, symbol, account_id),
    INDEX idx_pt_run       (run_id),
    INDEX idx_pt_account_date (account_id, trade_date, created_at),
    INDEX idx_pt_date_sym  (trade_date, symbol),
    INDEX idx_pt_account   (account_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
