CREATE TABLE IF NOT EXISTS risk_decisions (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    run_id          VARCHAR(32)   NOT NULL,
    trade_date      DATE          NOT NULL,
    symbol          VARCHAR(20)   NOT NULL,
    decision        VARCHAR(20)   NOT NULL,
    reason          VARCHAR(255)  NOT NULL,
    score_used      DOUBLE        NULL,
    score_source    VARCHAR(40)   NULL,
    entry_price     DOUBLE        NULL,
    proposed_shares INT           NULL,
    approved_shares INT           NULL,
    target_weight   DOUBLE        NULL,
    sector          VARCHAR(60)   NULL,
    conviction_score    DOUBLE       NULL,
    predicted_proba     DOUBLE       NULL,
    historical_win_rate DOUBLE       NULL,
    effective_probability DOUBLE     NULL,
    kelly_fraction      DOUBLE       NULL,
    sizing_method       VARCHAR(20)  NULL,
    correlation_blocker VARCHAR(20)  NULL,
    correlation_value   DOUBLE       NULL,
    company_idio_score      DOUBLE       NULL,
    macro_regime_score      DOUBLE       NULL,
    company_idio_signal_norm DOUBLE      NULL,
    macro_regime_signal_norm DOUBLE      NULL,
    company_idio_component  DOUBLE       NULL,
    macro_regime_component  DOUBLE       NULL,
    quant_component         DOUBLE       NULL,
    walk_forward_sentiment_weight DOUBLE NULL,
    walk_forward_macro_weight DOUBLE     NULL,
    walk_forward_quant_weight DOUBLE     NULL,
    calibration_run_id      VARCHAR(64)  NULL,
    calibration_source      VARCHAR(64)  NULL,
    account_id      VARCHAR(32)   NULL DEFAULT 'default',
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_rd_run       (run_id),
    INDEX idx_rd_date_sym  (trade_date, symbol),
    INDEX idx_rd_account   (account_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
