-- Sprint 7-B CN : limites dérivées, événements d'ajustement et couverture canonique.
CREATE TABLE IF NOT EXISTS cn_daily_price_limits (
  instrument_id BIGINT UNSIGNED NOT NULL,
  session_date DATE NOT NULL,
  reference_close DECIMAL(20,6) NULL,
  limit_up DECIMAL(20,6) NULL,
  limit_down DECIMAL(20,6) NULL,
  limit_pct DECIMAL(10,6) NULL,
  policy_code VARCHAR(64) NOT NULL,
  derivation_method VARCHAR(32) NOT NULL,
  is_rule_exception BOOLEAN NOT NULL DEFAULT FALSE,
  reached_up BOOLEAN NULL,
  reached_down BOOLEAN NULL,
  locked_up BOOLEAN NULL,
  locked_down BOOLEAN NULL,
  source VARCHAR(64) NOT NULL,
  observed_at DATETIME(6) NOT NULL,
  available_at DATETIME(6) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (instrument_id, session_date),
  KEY ix_cn_limits_session (session_date, policy_code),
  CONSTRAINT fk_cn_limits_instrument FOREIGN KEY (instrument_id) REFERENCES instruments(instrument_id),
  CONSTRAINT ck_cn_limits_order CHECK (limit_up IS NULL OR limit_down IS NULL OR limit_up >= limit_down),
  CONSTRAINT ck_cn_limits_pit CHECK (available_at >= observed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cn_corporate_actions (
  corporate_action_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  instrument_id BIGINT UNSIGNED NOT NULL,
  action_type VARCHAR(48) NOT NULL,
  announcement_date DATE NULL,
  ex_date DATE NOT NULL,
  record_date DATE NULL,
  payment_date DATE NULL,
  cash_amount DECIMAL(24,10) NULL,
  share_ratio DECIMAL(24,10) NULL,
  factor_value DECIMAL(24,10) NULL,
  previous_factor_value DECIMAL(24,10) NULL,
  classification_status VARCHAR(32) NOT NULL,
  source VARCHAR(64) NOT NULL,
  source_payload_hash CHAR(64) NOT NULL,
  observed_at DATETIME(6) NOT NULL,
  available_at DATETIME(6) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY uq_cn_ca_source_event (instrument_id, ex_date, source, source_payload_hash),
  KEY ix_cn_ca_instrument_date (instrument_id, ex_date),
  CONSTRAINT fk_cn_ca_instrument FOREIGN KEY (instrument_id) REFERENCES instruments(instrument_id),
  CONSTRAINT ck_cn_ca_pit CHECK (available_at >= observed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cn_canonical_coverage_metrics (
  coverage_run_id VARCHAR(96) NOT NULL,
  market_code VARCHAR(16) NOT NULL,
  board_code VARCHAR(32) NOT NULL,
  calendar_year SMALLINT NOT NULL,
  instrument_count INT NOT NULL,
  expected_bar_count BIGINT NOT NULL,
  observed_bar_count BIGINT NOT NULL,
  explicit_suspension_count BIGINT NOT NULL DEFAULT 0,
  factor_event_count BIGINT NOT NULL DEFAULT 0,
  coverage_ratio DECIMAL(12,8) NULL,
  status VARCHAR(24) NOT NULL,
  details_json JSON NULL,
  measured_at DATETIME(6) NOT NULL,
  PRIMARY KEY (coverage_run_id, market_code, board_code, calendar_year),
  KEY ix_cn_coverage_year_status (calendar_year, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
