CREATE TABLE `analyst_snapshot_collection_run` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `run_id` varchar(64) NOT NULL,
  `provider` varchar(16) NOT NULL,
  `started_at` datetime DEFAULT NULL,
  `finished_at` datetime DEFAULT NULL,
  `requested_symbols` int DEFAULT NULL,
  `successful_symbols` int DEFAULT NULL,
  `empty_symbols` int DEFAULT NULL,
  `failed_symbols` int DEFAULT NULL,
  `estimates_rows_inserted` int DEFAULT NULL,
  `targets_rows_inserted` int DEFAULT NULL,
  `recommendations_rows_inserted` int DEFAULT NULL,
  `rate_limit_count` int DEFAULT NULL,
  `temporary_error_count` int DEFAULT NULL,
  `schema_error_count` int DEFAULT NULL,
  `parse_error_count` int DEFAULT NULL,
  `eps_coverage` double DEFAULT NULL,
  `revenue_coverage` double DEFAULT NULL,
  `target_coverage` double DEFAULT NULL,
  `recommendation_coverage` double DEFAULT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'RUNNING' COMMENT 'RUNNING | COMPLETED | FAILED',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_run_run_id` (`run_id`),
  KEY `idx_run_started_at` (`started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci