CREATE TABLE IF NOT EXISTS `stock_analyst_eps_trend_history` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `provider` varchar(16) NOT NULL,
  `symbol` varchar(20) NOT NULL,
  `snapshot_date` date NOT NULL,
  `observed_at` datetime NOT NULL,
  `available_at` datetime NOT NULL,
  `ingestion_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `horizon_raw` varchar(8) NOT NULL,
  `horizon_normalized` varchar(24) NOT NULL,
  `fiscal_period_end` date DEFAULT NULL,
  `fiscal_year` smallint DEFAULT NULL,
  `fiscal_quarter` smallint DEFAULT NULL,
  `relative_horizon_only` tinyint(1) NOT NULL DEFAULT 1,
  `current_value` double DEFAULT NULL,
  `days_7_ago_value` double DEFAULT NULL,
  `days_30_ago_value` double DEFAULT NULL,
  `days_60_ago_value` double DEFAULT NULL,
  `days_90_ago_value` double DEFAULT NULL,
  `raw_payload_json` longtext,
  `raw_hash` varchar(64) DEFAULT NULL,
  `provider_schema_version` varchar(16) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_stock_analyst_eps_trend_history_daily_horizon` (`provider`,`symbol`,`snapshot_date`,`horizon_normalized`),
  KEY `idx_stock_analyst_eps_trend_history_symbol_date` (`symbol`,`snapshot_date`),
  KEY `idx_stock_analyst_eps_trend_history_available` (`symbol`,`available_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
