CREATE TABLE `stock_analyst_recommendation_history` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `provider` varchar(16) NOT NULL,
  `symbol` varchar(20) NOT NULL,
  `snapshot_date` date NOT NULL,
  `observed_at` datetime NOT NULL,
  `available_at` datetime NOT NULL,
  `ingestion_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `period_raw` varchar(8) NOT NULL COMMENT '0m | -1m | -2m | -3m (bucket fourni par Yahoo)',
  `strong_buy` int DEFAULT NULL,
  `buy` int DEFAULT NULL,
  `hold` int DEFAULT NULL,
  `sell` int DEFAULT NULL,
  `strong_sell` int DEFAULT NULL,
  `raw_payload_json` longtext,
  `raw_hash` varchar(64) DEFAULT NULL,
  `provider_schema_version` varchar(16) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_rec_provider_symbol_date_period` (`provider`,`symbol`,`snapshot_date`,`period_raw`),
  KEY `idx_rec_available_at` (`available_at`),
  KEY `idx_rec_symbol_date` (`symbol`,`snapshot_date`),
  KEY `idx_rec_observed_at` (`observed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci