CREATE TABLE `stock_analyst_estimate_history` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `provider` varchar(16) NOT NULL,
  `symbol` varchar(20) NOT NULL,
  `snapshot_date` date NOT NULL COMMENT 'Date NY de l''observation (date de collecte)',
  `observed_at` datetime NOT NULL COMMENT 'Moment réel où le collecteur a observé Yahoo (UTC)',
  `available_at` datetime NOT NULL COMMENT 'Prochaine séance de décision après observation (UTC)',
  `ingestion_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estimate_type` varchar(16) NOT NULL COMMENT 'EPS | REVENUE',
  `horizon_raw` varchar(8) NOT NULL COMMENT '0q | +1q | 0y | +1y (horizon Yahoo)',
  `horizon_normalized` varchar(24) NOT NULL COMMENT 'CURRENT_QUARTER | NEXT_QUARTER | CURRENT_YEAR | NEXT_YEAR',
  `fiscal_period_end` date DEFAULT NULL COMMENT 'NULL : Yahoo ne fournit pas l''identité fiscale',
  `fiscal_year` smallint DEFAULT NULL,
  `fiscal_quarter` smallint DEFAULT NULL,
  `relative_horizon_only` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'True si l''horizon est relatif sans identité fiscale',
  `avg_value` double DEFAULT NULL,
  `low_value` double DEFAULT NULL,
  `high_value` double DEFAULT NULL,
  `analyst_count` int DEFAULT NULL,
  `growth_value` double DEFAULT NULL,
  `raw_payload_json` longtext,
  `raw_hash` varchar(64) DEFAULT NULL,
  `provider_schema_version` varchar(16) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_est_provider_symbol_date_type_horizon` (`provider`,`symbol`,`snapshot_date`,`estimate_type`,`horizon_normalized`),
  KEY `idx_est_observed_at` (`observed_at`),
  KEY `idx_est_available_at` (`available_at`),
  KEY `idx_est_type_horizon` (`estimate_type`,`horizon_normalized`),
  KEY `idx_est_symbol_date` (`symbol`,`snapshot_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci