CREATE TABLE `stock_analyst_target_history` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `provider` varchar(16) NOT NULL,
  `symbol` varchar(20) NOT NULL,
  `snapshot_date` date NOT NULL,
  `observed_at` datetime NOT NULL,
  `available_at` datetime NOT NULL,
  `ingestion_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `current_price` double DEFAULT NULL,
  `target_low` double DEFAULT NULL,
  `target_mean` double DEFAULT NULL,
  `target_median` double DEFAULT NULL,
  `target_high` double DEFAULT NULL,
  `analyst_count` int DEFAULT NULL COMMENT 'NULL : Yahoo n''expose pas le nb d''analystes pour les targets',
  `raw_payload_json` longtext,
  `raw_hash` varchar(64) DEFAULT NULL,
  `provider_schema_version` varchar(16) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_tgt_provider_symbol_date` (`provider`,`symbol`,`snapshot_date`),
  KEY `idx_tgt_available_at` (`available_at`),
  KEY `idx_tgt_symbol_date` (`symbol`,`snapshot_date`),
  KEY `idx_tgt_observed_at` (`observed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci