CREATE TABLE IF NOT EXISTS alpha_trade.news_raw (
    article_id VARCHAR(128) NOT NULL COMMENT 'ID global unique, ex: alpaca:123456789',
    headline VARCHAR(1000) NOT NULL,
    summary TEXT NULL,
    content MEDIUMTEXT NULL,
    source VARCHAR(100) NOT NULL,
    author VARCHAR(255) NULL,
    published_at_utc DATETIME(6) NOT NULL,
    event_timestamp_utc DATETIME(6) NOT NULL,
    event_timestamp_ny DATETIME(6) NOT NULL,
    effective_trade_date DATE NOT NULL,
    market_session_tag ENUM('pre_market', 'regular', 'post_market', 'non_trading_day') NOT NULL,
    url VARCHAR(2083) NULL,
    ingestion_source VARCHAR(50) NOT NULL DEFAULT 'alpaca',
    dedupe_hash CHAR(64) NOT NULL,
    is_major_event TINYINT(1) NOT NULL DEFAULT 0,
    raw_payload JSON NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (article_id),
    UNIQUE KEY uk_news_raw_source_hash (ingestion_source, dedupe_hash),
    KEY idx_news_raw_trade_date (effective_trade_date),
    KEY idx_news_raw_published_utc (published_at_utc),
    KEY idx_news_raw_session_trade_date (market_session_tag, effective_trade_date),
    KEY idx_news_raw_source_published (ingestion_source, published_at_utc)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;