-- Sprint 6-A France : contrat PIT et séparation des périmètres de recherche.
-- Les tables sont créées vides. Le GO Sprint 5 n'autorise ni live ni serving.
CREATE TABLE IF NOT EXISTS fr_universe_runs (
  universe_run_id VARCHAR(96) NOT NULL PRIMARY KEY,
  market_code VARCHAR(16) NOT NULL DEFAULT 'FR_EQ',
  session_date DATE NOT NULL,
  decision_at DATETIME(6) NOT NULL,
  availability_lag_sessions SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  policy_version VARCHAR(64) NOT NULL,
  policy_fingerprint CHAR(64) NOT NULL,
  source_policy_version VARCHAR(64) NOT NULL,
  source_manifest_sha256 CHAR(64) NOT NULL,
  publication_tier VARCHAR(32) NOT NULL DEFAULT 'RESEARCH_J1',
  status VARCHAR(24) NOT NULL,
  observable_count INT UNSIGNED NOT NULL DEFAULT 0,
  training_count INT UNSIGNED NOT NULL DEFAULT 0,
  tradable_count INT UNSIGNED NOT NULL DEFAULT 0,
  servable_count INT UNSIGNED NOT NULL DEFAULT 0,
  details_json JSON NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  completed_at DATETIME(6) NULL,
  UNIQUE KEY uq_fr_universe_session_policy (market_code,session_date,policy_fingerprint,source_manifest_sha256),
  KEY ix_fr_universe_session_status (session_date,status),
  CONSTRAINT fk_fr_universe_market FOREIGN KEY (market_code) REFERENCES markets(market_code),
  CONSTRAINT ck_fr_universe_market CHECK (market_code='FR_EQ'),
  CONSTRAINT ck_fr_universe_tier CHECK (publication_tier='RESEARCH_J1'),
  CONSTRAINT ck_fr_universe_status CHECK (status IN ('PREPARED','COMPLETED','FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fr_universe_decisions (
  universe_run_id VARCHAR(96) NOT NULL,
  instrument_id BIGINT UNSIGNED NOT NULL,
  provider_symbol VARCHAR(128) NOT NULL,
  observable_state VARCHAR(16) NOT NULL,
  training_state VARCHAR(16) NOT NULL,
  tradable_state VARCHAR(16) NOT NULL,
  servable_state VARCHAR(16) NOT NULL,
  observable_reason VARCHAR(96) NOT NULL,
  training_reason VARCHAR(96) NOT NULL,
  tradable_reason VARCHAR(96) NOT NULL,
  servable_reason VARCHAR(96) NOT NULL,
  reasons_json JSON NOT NULL,
  source_manifest_eligible BOOLEAN NOT NULL,
  mic CHAR(4) NULL,
  history_sessions INT UNSIGNED NULL,
  liquidity_state VARCHAR(16) NOT NULL DEFAULT 'UNKNOWN',
  market_cap_state VARCHAR(16) NOT NULL DEFAULT 'UNKNOWN',
  spread_state VARCHAR(16) NOT NULL DEFAULT 'UNKNOWN',
  source_available_at DATETIME(6) NULL,
  details_json JSON NULL,
  PRIMARY KEY (universe_run_id,instrument_id),
  KEY ix_fr_universe_observable (universe_run_id,observable_state),
  KEY ix_fr_universe_training (universe_run_id,training_state),
  KEY ix_fr_universe_tradable (universe_run_id,tradable_state),
  CONSTRAINT fk_fr_universe_decision_run FOREIGN KEY (universe_run_id) REFERENCES fr_universe_runs(universe_run_id),
  CONSTRAINT fk_fr_universe_decision_instrument FOREIGN KEY (instrument_id) REFERENCES instruments(instrument_id),
  CONSTRAINT ck_fr_universe_observable_state CHECK (observable_state IN ('ELIGIBLE','INELIGIBLE','UNKNOWN','PROHIBITED')),
  CONSTRAINT ck_fr_universe_training_state CHECK (training_state IN ('ELIGIBLE','INELIGIBLE','UNKNOWN','PROHIBITED')),
  CONSTRAINT ck_fr_universe_tradable_state CHECK (tradable_state IN ('ELIGIBLE','INELIGIBLE','UNKNOWN','PROHIBITED')),
  CONSTRAINT ck_fr_universe_servable_state CHECK (servable_state IN ('ELIGIBLE','INELIGIBLE','UNKNOWN','PROHIBITED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
