CREATE TABLE IF NOT EXISTS alpha_trade.model_training_batch (
    batch_id               VARCHAR(64)  NOT NULL COMMENT 'Identifiant partage de la campagne d entrainement',
    status                 VARCHAR(20)  NOT NULL DEFAULT 'running' COMMENT 'running|completed|failed',
    command_line           TEXT         NOT NULL COMMENT 'Commande Model Factory reconstruite depuis argv',
    command_argv_json      TEXT         NOT NULL COMMENT 'Arguments CLI exacts recus par le processus',
    metadata_json          TEXT         NOT NULL COMMENT 'Options CLI et configuration effective serializees',
    comment                VARCHAR(200)  NOT NULL COMMENT 'Commentaire saisi par l utilisateur dans IHM',
    symbol_source          VARCHAR(32)  NOT NULL,
    universe_date          DATE         DEFAULT NULL,
    requested_symbol_count INT UNSIGNED DEFAULT NULL,
    training_start_date    DATE         DEFAULT NULL,
    training_end_date      DATE         DEFAULT NULL,
    started_at             DATETIME     NOT NULL,
    finished_at            DATETIME     DEFAULT NULL,
    symbols_completed      INT UNSIGNED NOT NULL DEFAULT 0,
    symbols_skipped        INT UNSIGNED NOT NULL DEFAULT 0,
    symbols_failed         INT UNSIGNED NOT NULL DEFAULT 0,
    failure_reason         TEXT         DEFAULT NULL,
    ic_rank                DOUBLE       DEFAULT NULL COMMENT 'IC Rank (Spearman) moyen du Global Ranking Model sur le walk-forward',
    ic_rank_std            DOUBLE       DEFAULT NULL COMMENT 'IC Rank Std Dev sur les splits WF',
    decile_spread_h3       DOUBLE       DEFAULT NULL COMMENT 'Decile Spread H3 : rendement Top 10% − Bottom 10% (moyen par date)',
    decile_spread_h5       DOUBLE       DEFAULT NULL COMMENT 'Decile Spread H5',
    decile_spread_h10      DOUBLE       DEFAULT NULL COMMENT 'Decile Spread H10',
    stacking_enabled       TINYINT(1)   NOT NULL DEFAULT 0 COMMENT 'Global Rank stacking injecté comme feature per-symbol (checkbox IHM)',
    symbols                VARCHAR(5000) DEFAULT NULL COMMENT 'Liste des symboles utilisés par le batch (séparés par virgule)',
    created_at             DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (batch_id),
    INDEX idx_model_training_batch_status_started (status, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Metadonnees par campagne d entrainement ML';