CREATE TABLE IF NOT EXISTS alpha_trade.model_governance (
    governance_id                    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    run_id                           VARCHAR(64)     NOT NULL,
    symbol                           VARCHAR(50)     NOT NULL,
    model_name                       VARCHAR(32)     NOT NULL COMMENT 'lstm_attention|lightgbm|catboost|global_model',
    `rank`                           INT             DEFAULT NULL,
    is_selected_model                TINYINT(1)      NOT NULL DEFAULT 0,
    selection_mode                   VARCHAR(32)     DEFAULT NULL COMMENT 'default_champion|auto_selected_champion|fallback_default_champion',
    selection_metric                 VARCHAR(32)     DEFAULT NULL COMMENT 'selection_score|business_score|auc',
    selection_score                  DOUBLE          DEFAULT NULL,
    model_status                     VARCHAR(32)     DEFAULT NULL,
    selection_eligible               TINYINT(1)      NOT NULL DEFAULT 0,
    eligibility_reason               VARCHAR(64)     DEFAULT NULL,
    reason                           VARCHAR(255)    DEFAULT NULL,
    inference_backend                VARCHAR(64)     DEFAULT NULL,
    backend_model_name               VARCHAR(64)     DEFAULT NULL,
    calibration_method               VARCHAR(32)     DEFAULT NULL,
    decision_threshold               DOUBLE          DEFAULT NULL,
    artifact_symbol                  VARCHAR(32)     DEFAULT NULL,
    checkpoint_path                  VARCHAR(500)    DEFAULT NULL,
    scaler_path                      VARCHAR(500)    DEFAULT NULL,
    model_path                       VARCHAR(500)    DEFAULT NULL,
    config_path                      VARCHAR(500)    DEFAULT NULL,
    calibrator_path                  VARCHAR(500)    DEFAULT NULL,
    val_auc                          DOUBLE          DEFAULT NULL,
    test_auc                         DOUBLE          DEFAULT NULL,
    wf_auc                           DOUBLE          DEFAULT NULL,
    val_threshold_business_score     DOUBLE          DEFAULT NULL,
    test_threshold_business_score    DOUBLE          DEFAULT NULL,
    wf_threshold_business_score      DOUBLE          DEFAULT NULL,    -- ML Sprint 7 — support ternaire
    num_classes                      TINYINT         DEFAULT 2 COMMENT '2=binaire, 3=ternaire long/flat/short',
    val_f1_macro                     DOUBLE          DEFAULT NULL COMMENT 'F1 macro (ternaire uniquement)',
    test_f1_macro                    DOUBLE          DEFAULT NULL COMMENT 'F1 macro (ternaire uniquement)',    created_at                       DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (governance_id),
    UNIQUE KEY uq_model_governance_run_symbol_model (run_id, symbol, model_name),
    INDEX idx_model_governance_symbol (symbol),
    INDEX idx_model_governance_run (run_id),
    INDEX idx_model_governance_selected (symbol, is_selected_model),
    INDEX idx_model_governance_rank (symbol, `rank`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Gouvernance challengers/champion persistée par run et symbole';

