import pymysql
conn = pymysql.connect(host="localhost", user="root", password="root", database="alpha_trade", charset="utf8mb4")
cur = conn.cursor()
cur.execute("SELECT data_source, COUNT(*) FROM stock_bars_daily GROUP BY data_source")
print("data sources:", cur.fetchall())
cur.execute("SELECT MAX(date) FROM stock_bars_daily")
print("max date:", cur.fetchone())
cur.execute("SELECT COUNT(*) FROM stock_bars_daily WHERE symbol='SPY' AND date >= '2026-02-01'")
print("SPY bars 2026:", cur.fetchone())
cur.execute("SELECT COUNT(*) FROM stock_bars_daily WHERE symbol='AAPL' AND date >= '2026-02-01'")
print("AAPL bars 2026:", cur.fetchone())
cur.execute("SELECT COUNT(*) FROM stock_metadata WHERE market_cap IS NOT NULL")
print("metadata with cap:", cur.fetchone())
conn.close()
print("done")
