"""Sprint S4 (A-019) — générateur automatique de la matrice data-lineage.

Produit ``doc/data_lineage_matrix.md`` à partir de la spécification interne
:data:`LINEAGE_SPEC` (single source of truth). Peut également mettre à jour
le bloc balisé ``provider_table_matrix`` de :file:`doc/service.md`.

Modes :

- défaut : régénère ``doc/data_lineage_matrix.md`` (écrit si différent).
- ``--check`` : exit 1 si le fichier diverge (utilisable en CI).
- ``--target service-md`` : ne touche qu'au bloc balisé de ``doc/service.md``.
- ``--verify-completeness`` : échoue si une table de
  ``database/sql/all_tables.py`` n'apparaît pas dans la spec.

Garanties d'idempotence : ordre stable, byte-identique entre deux runs
sans modification de la spec.

Usage :

.. code-block:: powershell

    python scripts/generate_data_lineage.py --check
    python scripts/generate_data_lineage.py --target service-md
"""
from __future__ import annotations

import argparse
import logging
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

LOGGER = logging.getLogger("generate_data_lineage")

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "doc" / "data_lineage_matrix.md"
SERVICE_MD = ROOT / "doc" / "service.md"
ALL_TABLES_PY = ROOT / "database" / "sql" / "all_tables.py"

GENERATED_BANNER = (
    "<!-- generated by scripts/generate_data_lineage.py — do not edit by hand -->"
)
SERVICE_BLOCK_BEGIN = "<!-- BEGIN provider_table_matrix -->"
SERVICE_BLOCK_END = "<!-- END provider_table_matrix -->"


# ---------------------------------------------------------------------------
# Spécification — single source of truth
# ---------------------------------------------------------------------------

@dataclass(frozen=True, slots=True)
class LineageEntry:
    table: str
    producer: str
    consumers: str
    upstream: str
    provider_active: str
    frequency: str
    criticality: str
    section: str
    note: str = ""


@dataclass(frozen=True, slots=True)
class ProviderEntry:
    provider: str
    service_module: str
    tables: tuple[str, ...]
    mode: str
    criticality: str


SECTIONS_ORDER = (
    "1. Données de marché",
    "2. Scoring & sélection",
    "3. Sentiment & ML",
    "4. Risk & exécution",
    "5. Corporate actions",
    "6. Backtesting & calibration",
)

LINEAGE_SPEC: tuple[LineageEntry, ...] = (
    # 1. Données de marché
    LineageEntry("stock_assets",
                 "dataIntegrityEngine.import_alpaca_assets",
                 "screener, selector, ihm",
                 "Alpaca", "Alpaca (toujours)", "daily", "P1",
                 SECTIONS_ORDER[0]),
    LineageEntry("stock_bars_daily *(provider=eodhd, défaut)*",
                 "dataIntegrityEngine.import_eodhd_bar",
                 "screener, selector, modelFactory, backtesting",
                 "EODHD bulk EOD", "**EODHD (primaire)**", "daily", "P1",
                 SECTIONS_ORDER[0]),
    LineageEntry("stock_bars_daily *(provider=alpaca, rétrocompat)*",
                 "dataIntegrityEngine.import_alpaca_bar",
                 "idem", "Alpaca IEX", "Alpaca (rétrocompat)", "daily", "P1",
                 SECTIONS_ORDER[0]),
    LineageEntry("stock_bars (1D, provider=eodhd)",
                 "import_eodhd_bar + backfill_eodhd_history",
                 "selector, modelFactory",
                 "EODHD `/eod`", "**EODHD (primaire)**", "daily / one-shot", "P1",
                 SECTIONS_ORDER[0]),
    LineageEntry("stock_bars (intraday, provider=alpaca)",
                 "dataIntegrityEngine.import_alpaca_bar (intraday)",
                 "execution_engine.tca", "Alpaca IEX",
                 "Alpaca (toujours pour l'intraday)", "intraday", "P2",
                 SECTIONS_ORDER[0]),
    LineageEntry("stock_quote_snapshots",
                 "dataIntegrityEngine.sync_latest_quotes",
                 "selector (`spread_bps`)", "Alpaca IEX",
                 "Alpaca (toujours)", "daily", "P1",
                 SECTIONS_ORDER[0]),
    LineageEntry("stock_metadata",
                 "dataIntegrityEngine.update_sector",
                 "screener, selector (filtres market_cap, sector)", "Finnhub",
                 "Finnhub (toujours)", "weekly", "P2",
                 SECTIONS_ORDER[0]),
    LineageEntry("earnings_calendar",
                 "dataIntegrityEngine.sync_earnings_calendar",
                 "selector, risk_management (blackout)", "Finnhub",
                 "Finnhub (toujours)", "daily", "P2",
                 SECTIONS_ORDER[0]),
    # 2. Scoring & sélection
    LineageEntry("stock_scores",
                 "screener", "selector, risk_management, backtesting",
                 "computed", "—", "daily", "P1",
                 SECTIONS_ORDER[1]),
    LineageEntry("selector_alpha_candidates",
                 "selector.alpha_scanner", "risk_management, ihm",
                 "computed", "—", "daily", "P1",
                 SECTIONS_ORDER[1]),
    LineageEntry("screener_run_summaries",
                 "screener", "ihm (audit)",
                 "computed", "—", "daily", "P3",
                 SECTIONS_ORDER[1]),
    # 3. Sentiment & ML
    LineageEntry("news_articles",
                 "event_sentiment.importer", "sentiment_pipeline",
                 "Alpaca News", "Alpaca", "daily", "P2",
                 SECTIONS_ORDER[2]),
    LineageEntry("sentiment_scores",
                 "event_sentiment.signal_aggregator", "risk_management",
                 "computed (FinBERT)", "—", "daily", "P2",
                 SECTIONS_ORDER[2]),
    LineageEntry("model_predictions",
                 "modelFactory.run_predict", "risk_management",
                 "computed (LightGBM/CatBoost/LSTM)", "—", "daily", "P1",
                 SECTIONS_ORDER[2]),
    LineageEntry("model_governance",
                 "modelFactory.champion_selection", "run_predict",
                 "computed", "—", "weekly", "P1",
                 SECTIONS_ORDER[2]),
    LineageEntry("model_metrics_full",
                 "modelFactory.evaluation", "governance, ihm",
                 "computed", "—", "weekly", "P3",
                 SECTIONS_ORDER[2]),
    LineageEntry("ml_drift_runs *(Phase 7.4 + Sprint S4 gate)*",
                 "modelFactory.drift_monitor + drift_policy",
                 "ops alerting, risk_management (S8)",
                 "computed", "—", "daily", "P2",
                 SECTIONS_ORDER[2]),
    # 4. Risk & exécution
    LineageEntry("risk_runs", "risk_management", "execution_engine, ihm",
                 "computed", "—", "daily", "P1", SECTIONS_ORDER[3]),
    LineageEntry("risk_decisions", "risk_management", "execution_engine",
                 "computed", "—", "daily", "P1", SECTIONS_ORDER[3]),
    LineageEntry("execution_runs", "execution_engine.executor",
                 "reconciliation, ihm, watcher",
                 "computed", "—", "daily", "P1", SECTIONS_ORDER[3]),
    LineageEntry("execution_orders", "execution_engine.executor",
                 "reconciliation, tca",
                 "broker (Alpaca)", "Alpaca", "intraday", "P1", SECTIONS_ORDER[3]),
    LineageEntry("execution_positions", "execution_engine.executor",
                 "risk_management (J+1 equity)",
                 "broker", "Alpaca", "intraday", "P1", SECTIONS_ORDER[3]),
    LineageEntry("execution_audit_events", "execution_engine.executor",
                 "reconciliation",
                 "computed", "—", "on-event", "P2", SECTIONS_ORDER[3]),
    LineageEntry("execution_kill_switch_runs *(Phase 5.2.c)*",
                 "execution_engine cancel-all", "watcher, ihm",
                 "computed", "—", "manual", "P1", SECTIONS_ORDER[3]),
    LineageEntry("execution_locks", "watcher / executor", "mutual exclusion",
                 "computed", "—", "on-event", "P1", SECTIONS_ORDER[3]),
    LineageEntry("watcher_heartbeats *(Phase 1.2)*",
                 "watcher.protection_watcher", "ihm, alerting",
                 "computed", "—", "continuous", "P1", SECTIONS_ORDER[3]),
    LineageEntry("shadow_drift_runs *(Phase 7.7)*",
                 "risk_management.shadow_compare", "ops review",
                 "computed", "—", "manual", "P3", SECTIONS_ORDER[3]),
    LineageEntry("broker_positions_snapshots *(Sprint S3)*",
                 "execution_engine.snapshots", "risk_management (PnL J)",
                 "broker", "Alpaca", "daily", "P1", SECTIONS_ORDER[3]),
    # 5. Corporate actions
    LineageEntry("corporate_actions_events", "corporate_actions.engine",
                 "reconciliation, accounting",
                 "EODHD div/split, Alpaca CA, Yahoo (cross-check)",
                 "**EODHD (primaire)**", "daily", "P1", SECTIONS_ORDER[4]),
    LineageEntry("corporate_actions_audit_runs *(Phase 5.3.b)*",
                 "corporate_actions.reconciliation", "ops",
                 "computed", "—", "daily", "P2", SECTIONS_ORDER[4]),
    LineageEntry("portfolio_cash_ledger",
                 "corporate_actions.processors",
                 "backtesting (`total_return_with_dividends`)",
                 "computed", "—", "on-event", "P2", SECTIONS_ORDER[4]),
    # 6. Backtesting & calibration
    LineageEntry("backtest_runs", "backtesting.cli", "ihm",
                 "computed", "—", "manual", "P3", SECTIONS_ORDER[5]),
    LineageEntry("weights_calibration_runs *(Phase 7.2)*",
                 "backtesting.weights_calibration",
                 "risk_management (poids cible)",
                 "computed", "—", "weekly", "P3", SECTIONS_ORDER[5]),
    LineageEntry("cleaning_audit_runs",
                 "dataIntegrityEngine.data_sanitizer_daily", "ops, ihm",
                 "computed (cross-check Stooq best-effort)", "Stooq", "daily", "P2",
                 SECTIONS_ORDER[5]),
    LineageEntry("cleaning_audit_quotes_runs *(Phase 3.1)*",
                 "sync_latest_quotes", "ops",
                 "computed", "—", "daily", "P2", SECTIONS_ORDER[5]),
    LineageEntry("cleaning_audit_earnings_runs *(Phase 3.1)*",
                 "sync_earnings_calendar", "ops",
                 "computed", "—", "daily", "P3", SECTIONS_ORDER[5]),
)


PROVIDER_SPEC: tuple[ProviderEntry, ...] = (
    ProviderEntry("eodhd", "service/eodhd/",
                  ("stock_bars_daily(provider=eodhd)", "stock_bars(1D)",
                   "corporate_actions_events(div/split)"),
                  "bulk EOD + on-demand", "P1"),
    ProviderEntry("alpaca", "service/alpaca/",
                  ("stock_assets", "stock_bars(intraday)",
                   "stock_quote_snapshots", "news_articles",
                   "execution_orders", "execution_positions",
                   "broker_positions_snapshots"),
                  "REST + WS", "P1"),
    ProviderEntry("finnhub", "service/finnhub/",
                  ("stock_metadata", "earnings_calendar"),
                  "REST throttle", "P2"),
    ProviderEntry("yahoo", "service/yahoo/",
                  ("corporate_actions_events (cross-check)",),
                  "best-effort", "P3"),
    ProviderEntry("stooq", "service/stooq/",
                  ("cleaning_audit_runs.cross_check_anomalies",),
                  "best-effort", "P3"),
    ProviderEntry("tiingo", "service/tiingo/",
                  ("(réservé, pas de table prod)",),
                  "inactif", "—"),
)


HEADER_NOTES = """\
> **Audience** : développeurs et opérateurs.
> **Objectif** : référencer pour chaque table métier qui l'écrit, qui la lit,
> et la criticité opérationnelle. Mise à jour requise à chaque ajout de table
> (cf. `doc/guide_add_new_table.md`).
>
> **Provider OHLCV primaire actuel** : `EODHD` (cf. `config.yaml ›
> market_data.bars_provider`). Le mode `alpaca` est conservé en
> rétrocompatibilité (colonne « provider actif » ci-dessous).

> **Maintenance** : régénérer via `python scripts/generate_data_lineage.py`.
> En CI : `python scripts/generate_data_lineage.py --check`.
"""

FOOTER_NOTES = """\
## 7. Notes de couplages critiques

- **SPY = univers + calendrier** : la migration vers
  `pandas_market_calendars` (Phase 3.1) a découplé le calendrier ; SPY reste
  utilisé comme benchmark / univers ML.
- **`stock_metadata.market_cap`** : Finnhub free figé ; consommé avec TTL via
  `market_cap_refreshed_at` depuis Phase 3.
- **Convention `data_adjustment='split'`** matérialisée par CHECK SQL depuis
  Phase 1.1 sur `stock_bars` et `stock_bars_daily`.
- **Cross-check Stooq** *(Phase 7.3)* : best-effort, anomalies persistées
  dans `cleaning_audit_runs.cross_check_anomalies` (JSON).
- **EODHD provider switch** *(Phase 6)* : `market_data.bars_provider`
  (`alpaca` | `eodhd`) contrôle quel module daily est actif. L'autre devient
  no-op au niveau de `main()` pour interdire toute double-écriture.
- **EODHD source primaire dividendes** *(Phase 6)* : la factory
  `corporate_actions.provider.build_corporate_action_provider` sélectionne
  `EodhdCorporateActionProvider` quand `bars_provider=eodhd`.
- **Cohabitation `data_source` mixte** : `stock_bars_daily` peut contenir
  simultanément `alpaca_iex` ET `eodhd_eod` sur la même `(symbol, date)`.
- **Drift gate ML** *(Sprint S4 / A-021)* : `modelFactory.drift_policy`
  écrit un événement `ml_drift_runs.payload.gate_action='kill_switch_ml'`
  quand le drift atteint le statut `ALERT` ; le flag remonte dans
  `run_summary` ML (`ml_kill_switch_active`).

---

**Réf.** : audit_global §7.6, §7.9 ; `doc/database.md` ;
`doc/guide_add_new_table.md` ; `prompt/iex/plan_eodhd.md` (Phases 1-6) ;
`prompt/tod/14_sprint_S4_delivery_report.md`.
"""


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

def _render_table(rows: list[LineageEntry]) -> str:
    headers = ("Table", "Producteur (CLI / module)", "Consommateurs",
               "Source upstream", "Provider actif", "Fréquence", "Criticité")
    lines = ["| " + " | ".join(headers) + " |",
             "|" + "|".join(["---"] * len(headers)) + "|"]
    for r in rows:
        lines.append("| " + " | ".join([
            r.table, r.producer, r.consumers, r.upstream,
            r.provider_active, r.frequency, r.criticality,
        ]) + " |")
    return "\n".join(lines)


def render_lineage_markdown(*, primary_provider: str = "eodhd") -> str:
    parts: list[str] = []
    parts.append("# Matrice Data Lineage — table ↔ producteur ↔ consommateurs (Phase 7.6)")
    parts.append("")
    parts.append(GENERATED_BANNER)
    parts.append("")
    parts.append(f"<!-- primary_provider: {primary_provider} -->")
    parts.append("")
    parts.append(HEADER_NOTES.rstrip())
    parts.append("")
    parts.append("---")
    parts.append("")
    parts.append("## Légende")
    parts.append("")
    parts.append("- **Fréquence** : `daily` / `intraday` / `on-event` / `manual`.")
    parts.append("- **Criticité** : `P1` (live trading bloque sans), `P2` (pipeline dégradé),")
    parts.append("  `P3` (analytics / audit uniquement).")
    parts.append("")
    parts.append("---")
    parts.append("")
    by_section: dict[str, list[LineageEntry]] = {s: [] for s in SECTIONS_ORDER}
    for entry in LINEAGE_SPEC:
        by_section[entry.section].append(entry)
    for section in SECTIONS_ORDER:
        rows = by_section[section]
        parts.append(f"## {section}")
        parts.append("")
        parts.append(_render_table(rows))
        parts.append("")
    parts.append(FOOTER_NOTES.rstrip())
    parts.append("")
    return "\n".join(parts)


def render_provider_block() -> str:
    headers = ("Provider", "Module(s) service", "Tables alimentées (DB)",
               "Mode appel", "Criticité")
    lines = [SERVICE_BLOCK_BEGIN,
             GENERATED_BANNER,
             "",
             "### 10. Matrice Provider → Tables alimentées",
             "",
             "| " + " | ".join(headers) + " |",
             "|" + "|".join(["---"] * len(headers)) + "|"]
    for p in PROVIDER_SPEC:
        tables = ", ".join(f"`{t}`" for t in p.tables)
        lines.append(f"| `{p.provider}` | `{p.service_module}` | {tables} | {p.mode} | {p.criticality} |")
    lines.append("")
    lines.append("> Matrice détaillée table-par-table : voir "
                 "[`doc/data_lineage_matrix.md`](data_lineage_matrix.md).")
    lines.append("")
    lines.append(SERVICE_BLOCK_END)
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Discovery / completeness
# ---------------------------------------------------------------------------

_TABLE_RE = re.compile(r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?[\"`]?(\w+)[\"`]?",
                       re.IGNORECASE)


def discover_tables(path: Path = ALL_TABLES_PY) -> set[str]:
    if not path.exists():
        return set()
    txt = path.read_text(encoding="utf-8", errors="replace")
    return {m.group(1).lower() for m in _TABLE_RE.finditer(txt)}


def _spec_table_names() -> set[str]:
    names: set[str] = set()
    for entry in LINEAGE_SPEC:
        # Strip annotations like " *(...)*" or "(provider=...)"
        base = entry.table
        base = re.sub(r"\s*\*\(.*?\)\*", "", base)
        base = re.sub(r"\s*\(.*?\)", "", base)
        names.add(base.strip().lower())
    return names


# ---------------------------------------------------------------------------
# I/O helpers
# ---------------------------------------------------------------------------

def write_if_changed(path: Path, content: str) -> bool:
    """Écrit ``content`` dans ``path`` uniquement s'il y a une différence.

    Retourne ``True`` si une écriture a eu lieu, ``False`` sinon.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def replace_block(text: str, *, begin: str, end: str, new_block: str) -> str:
    """Remplace ou insère un bloc balisé ``begin``..``end``."""
    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.DOTALL)
    if pattern.search(text):
        return pattern.sub(new_block, text)
    sep = "" if text.endswith("\n") else "\n"
    return text + sep + "\n" + new_block + "\n"


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__.split("\n", maxsplit=1)[0])
    p.add_argument("--output", type=Path, default=DEFAULT_OUTPUT,
                   help=f"Fichier de sortie (défaut: {DEFAULT_OUTPUT.relative_to(ROOT)})")
    p.add_argument("--target", choices=("lineage", "service-md", "all"),
                   default="lineage",
                   help="Cible de génération : lineage (data_lineage_matrix.md), "
                        "service-md (bloc balisé de doc/service.md), all (les deux).")
    p.add_argument("--service-md-path", type=Path, default=SERVICE_MD,
                   help="Chemin de doc/service.md (override pour tests).")
    p.add_argument("--check", action="store_true",
                   help="N'écrit pas ; exit 1 si le fichier diverge.")
    p.add_argument("--verify-completeness", action="store_true",
                   help="Échoue si une table de all_tables.py n'apparaît pas dans la spec.")
    p.add_argument("--primary-provider", default="eodhd",
                   choices=("eodhd", "alpaca"),
                   help="Provider OHLCV primaire mentionné dans le bandeau.")
    p.add_argument("--log-level", default="INFO",
                   choices=("DEBUG", "INFO", "WARNING", "ERROR"))
    return p


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    logging.basicConfig(level=getattr(logging, args.log_level), format="%(levelname)s %(message)s")

    if args.verify_completeness:
        sql_tables = discover_tables()
        spec_tables = _spec_table_names()
        missing = sorted(t for t in sql_tables if t not in spec_tables)
        if missing:
            LOGGER.error("Tables présentes dans all_tables.py mais absentes de LINEAGE_SPEC: %s",
                         ", ".join(missing))
            return 2

    targets = {"lineage", "service-md"} if args.target == "all" else {args.target}
    diverged = False

    if "lineage" in targets:
        content = render_lineage_markdown(primary_provider=args.primary_provider)
        if args.check:
            existing = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
            if existing != content:
                LOGGER.error("data_lineage_matrix.md is out of date — re-run scripts/generate_data_lineage.py")
                diverged = True
            else:
                LOGGER.info("data_lineage_matrix.md up-to-date")
        else:
            changed = write_if_changed(args.output, content)
            LOGGER.info("data_lineage_matrix.md %s", "rewritten" if changed else "unchanged")

    if "service-md" in targets:
        block = render_provider_block()
        path = args.service_md_path
        existing_md = path.read_text(encoding="utf-8") if path.exists() else ""
        new_md = replace_block(existing_md, begin=SERVICE_BLOCK_BEGIN,
                               end=SERVICE_BLOCK_END, new_block=block)
        if args.check:
            if existing_md != new_md:
                LOGGER.error("doc/service.md provider block is out of date — re-run with --target service-md")
                diverged = True
            else:
                LOGGER.info("doc/service.md provider block up-to-date")
        else:
            changed = write_if_changed(path, new_md)
            LOGGER.info("doc/service.md provider block %s",
                        "rewritten" if changed else "unchanged")

    return 1 if diverged else 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())

