CREATE TABLE IF NOT EXISTS execution_broker_orders (
    id                 BIGINT AUTO_INCREMENT PRIMARY KEY,
    request_id         VARCHAR(32) NOT NULL,
    exec_run_id        VARCHAR(32) NOT NULL,
    account_id         VARCHAR(32) NOT NULL,
    broker_order_id    VARCHAR(64) NOT NULL,
    client_order_id    VARCHAR(64) NULL,
    symbol             VARCHAR(20) NOT NULL,
    side               VARCHAR(10) NOT NULL,
    qty                DOUBLE NOT NULL,
    filled_qty         DOUBLE NOT NULL DEFAULT 0,
    avg_fill_price     DOUBLE NULL,
    raw_status         VARCHAR(32) NOT NULL,
    normalized_status  VARCHAR(32) NOT NULL,
    order_type         VARCHAR(20) NOT NULL,
    limit_price        DOUBLE NULL,
    stop_price         DOUBLE NULL,
    trail_percent      DOUBLE NULL,
    raw_payload_json   JSON NULL,
    raw_response_json  JSON NULL,
    submitted_at       TIMESTAMP NULL,
    last_seen_at       TIMESTAMP NULL,
    UNIQUE KEY uq_ebo_broker_order_id (broker_order_id),
    KEY idx_ebo_request_id (request_id),
    KEY idx_ebo_exec_run (exec_run_id),
    KEY idx_ebo_account_status (account_id, normalized_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
