CREATE TABLE IF NOT EXISTS execution_orders (
    id                BIGINT AUTO_INCREMENT PRIMARY KEY,
    exec_run_id       VARCHAR(32) NOT NULL,
    risk_run_id       VARCHAR(32) NULL,
    symbol            VARCHAR(20) NOT NULL,
    intent_id         VARCHAR(32) NOT NULL,
    parent_intent_id  VARCHAR(32) NULL,
    intent_role       VARCHAR(20) NOT NULL,
    idempotency_key   VARCHAR(64) NOT NULL UNIQUE,
    broker_mode       VARCHAR(10) NOT NULL,
    broker_order_id   VARCHAR(64) NULL,
    client_order_id   VARCHAR(64) NULL,
    side              VARCHAR(10) NOT NULL,
    qty               DOUBLE NOT NULL,
    filled_qty        DOUBLE NOT NULL DEFAULT 0,
    avg_fill_price    DOUBLE NULL,
    order_type        VARCHAR(20) NOT NULL,
    limit_price       DOUBLE NULL,
    stop_price        DOUBLE NULL,
    trail_percent     DOUBLE NULL,
    decision_price    DOUBLE NULL,
    status            VARCHAR(20) NOT NULL DEFAULT 'NEW',
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_eo_run (exec_run_id),
    INDEX idx_eo_symbol (symbol),
    INDEX idx_eo_parent (parent_intent_id),
    INDEX idx_eo_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

