CREATE TABLE IF NOT EXISTS execution_targets_snapshot (
    id                    BIGINT AUTO_INCREMENT PRIMARY KEY,
    exec_run_id           VARCHAR(32) NOT NULL,
    account_id            VARCHAR(32) NOT NULL DEFAULT 'default',
    risk_run_id           VARCHAR(32) NOT NULL,
    trade_date            DATE NOT NULL,
    symbol                VARCHAR(20) NOT NULL,
    decision_rank         INT NULL,
    side                  VARCHAR(10) NULL,
    target_shares         INT NOT NULL,
    entry_price           DOUBLE NOT NULL,
    target_weight         DOUBLE NOT NULL,
    sector                VARCHAR(60) NULL,
    conviction_score      DOUBLE NULL,
    sizing_method         VARCHAR(20) NULL,
    kelly_fraction        DOUBLE NULL,
    atr_20                DOUBLE NULL,
    price_asof_date       DATE NULL,
    atr_asof_date         DATE NULL,
    stop_price_initial    DOUBLE NULL,
    risk_per_share        DOUBLE NULL,
    risk_budget_dollars   DOUBLE NULL,
    initial_risk_dollars  DOUBLE NULL,
    target_notional       DOUBLE NULL,
    created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_ets_run (exec_run_id),
    INDEX idx_ets_account (account_id),
    INDEX idx_ets_symbol (symbol)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

